modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"
issueTrackerURL = "https://github.com/dima-dencep/rubidium-extra/issues"

[[mods]]
modId = "sodiumextra"
version = "${version}"
displayName = "Rubidium Extra"
logoFile= "icon.png"
updateJSONURL = "https://api.modrinth.com/updates/rubidium-extra/forge_updates.json"
authors = "dima_dencep, FlashyReese"
credits = "AMereBagatelle, DragonEggBedrockBreaking, EatMyVenom, HarvelsX, Kichura, Madis0, Paint_Ninja"
displayURL = "https://curseforge.com/minecraft/mc-mods/rubidium-extra"
description = "Features that shouldn't be in Rubidium."

[[dependencies.sodiumextra]]
modId = "rubidium"
mandatory = true
versionRange = "[0.2.13,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sodiumextra]]
modId = "minecraft" # Gives a friendlier error message when installed on the wrong MC version
mandatory = true
versionRange = "[1.16,)" # Allows 1.16
ordering = "NONE"
side = "CLIENT"
