modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"
issueTrackerURL = "https://github.com/dima-dencep/rubidium-extra/issues"

[[mods]]
displayTest = "IGNORE_SERVER_VERSION"
modId = "embeddium_extra"
version = "${version}"
displayName = "Embeddium Extra"
logoFile = "icon.png"
updateJSONURL = "https://api.modrinth.com/updates/rubidium-extra/forge_updates.json"
authors = "dima_dencep, FlashyReese"
credits = "AMereBagatelle, DragonEggBedrockBreaking, EatMyVenom, HarvelsX, Kichura, Madis0, Paint_Ninja"
displayURL = "https://curseforge.com/minecraft/mc-mods/rubidium-extra"
description = "Features that shouldn't be in Embeddium."
provides = ["sodium-extra", "sodium_extra"]

[[dependencies.embeddium_extra]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.embeddium_extra]]
modId = "embeddium"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.embeddium_extra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"
