name: Crash Report
description: File a crash report
labels: crash
body:
  - type: checkboxes
    id: unique
    attributes:
      label: Make sure you are not opening a duplicate.
      options:
        - label: "[I have searched the issue tracker](https://github.com/dima-dencep/rubidium-extra/issues) and did not find an issue describing my crash."
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Are you using the latest version of the mod? If not, try updating to see if it resolves your issue. You can [find the latest versions here](https://github.com/dima-dencep/rubidium-extra/releases)."
  - type: input
    id: version-mc
    attributes:
      label: Minecraft version.
      placeholder: ex. 1.18.2
    validations:
      required: true
  - type: input
    id: version-rubidium-extra
    attributes:
      label: Rubidium Extra version.
      placeholder: ex. 0.4.8
    validations:
      required: true
  - type: input
    id: version-rubidium
    attributes:
      label: Rubidium version.
      placeholder: ex. 0.2.8
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder:  ex. I disabled some particles and my game crashed.
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Relevant logs
      description: Please upload your latest.log and crash report log (both files can be found inside theirs respective directories in your Minecraft root folder, like the mods one) to any pastebin service ex. gist.github.com, hastebin.com, pastebin.ubuntu.com, paste.ee or paste.gg
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Provide a list of any other mods you are using, along with their respective versions. If you have any screenshots, videos, or other information that you feel is necessary to explain the issue, feel free to attach them here.
